# Generated by Django 5.2.14 on 2026-05-27 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('scope_1', 'Scope 1'), ('scope_2', 'Scope 2'), ('scope_3', 'Scope 3')], max_length=20)),
                ('category', models.CharField(choices=[('fuel_combustion', 'Fuel combustion'), ('purchased_electricity', 'Purchased electricity'), ('business_travel', 'Business travel')], max_length=40)),
                ('subcategory', models.CharField(max_length=60)),
                ('unit', models.CharField(max_length=30)),
                ('co2e_kg_per_unit', models.DecimalField(decimal_places=6, max_digits=18)),
                ('region', models.CharField(blank=True, default='', max_length=50)),
                ('source', models.CharField(blank=True, default='', max_length=200)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('sap_csv', 'SAP CSV'), ('utility_csv', 'Utility CSV'), ('travel_api', 'Travel API')], max_length=30)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='received', max_length=20)),
                ('created_by', models.CharField(blank=True, default='', max_length=200)),
                ('source_label', models.CharField(blank=True, default='', max_length=200)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('raw_record_count', models.PositiveIntegerField(default=0)),
                ('parsed_record_count', models.PositiveIntegerField(default=0)),
                ('failed_record_count', models.PositiveIntegerField(default=0)),
                ('activity_record_count', models.PositiveIntegerField(default=0)),
                ('anomaly_record_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('summary', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('timezone', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('sap_csv', 'SAP CSV'), ('utility_csv', 'Utility CSV'), ('travel_api', 'Travel API')], max_length=30)),
                ('row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('source_external_id', models.CharField(blank=True, default='', max_length=200)),
                ('raw_payload', models.JSONField()),
                ('raw_text', models.TextField(blank=True, default='')),
                ('raw_hash_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('parsed', 'Parsed'), ('failed', 'Failed')], default='parsed', max_length=20)),
                ('parse_errors', models.JSONField(blank=True, default=list)),
                ('ingestion_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='core.ingestionjob')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('sap_csv', 'SAP CSV'), ('utility_csv', 'Utility CSV'), ('travel_api', 'Travel API')], max_length=30)),
                ('source_external_id', models.CharField(blank=True, default='', max_length=200)),
                ('scope', models.CharField(choices=[('scope_1', 'Scope 1'), ('scope_2', 'Scope 2'), ('scope_3', 'Scope 3')], max_length=20)),
                ('category', models.CharField(choices=[('fuel_combustion', 'Fuel combustion'), ('purchased_electricity', 'Purchased electricity'), ('business_travel', 'Business travel')], max_length=40)),
                ('subcategory', models.CharField(max_length=60)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('source_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('source_unit', models.CharField(blank=True, default='', max_length=30)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('normalized_unit', models.CharField(max_length=30)),
                ('emission_factor_snapshot', models.JSONField(blank=True, default=dict)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('activity_metadata', models.JSONField(blank=True, default=dict)),
                ('anomaly_flags', models.JSONField(blank=True, default=list)),
                ('confidence_score', models.DecimalField(decimal_places=3, default=0.5, max_digits=4)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, default='', max_length=200)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, default='', max_length=200)),
                ('last_edited_at', models.DateTimeField(blank=True, null=True)),
                ('last_edited_by', models.CharField(blank=True, default='', max_length=200)),
                ('emission_factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.emissionfactor')),
                ('ingestion_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ingestionjob')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.plant')),
                ('raw_record', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='activity_record', to='core.rawrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AddField(
            model_name='ingestionjob',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AddField(
            model_name='emissionfactor',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.CreateModel(
            name='ActivityChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change_type', models.CharField(choices=[('edit', 'Edit'), ('system_recalc', 'System recalculation')], max_length=30)),
                ('changed_by', models.CharField(max_length=200)),
                ('reason', models.TextField(blank=True, default='')),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('changed_fields', models.JSONField(default=list)),
                ('activity_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='core.activityrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject')], max_length=20)),
                ('decided_by', models.CharField(max_length=200)),
                ('reason', models.TextField(blank=True, default='')),
                ('activity_snapshot', models.JSONField(default=dict)),
                ('activity_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_decisions', to='core.activityrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'decision', 'created_at'], name='core_review_tenant__97bea9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='rawrecord',
            index=models.Index(fields=['tenant', 'ingestion_job', 'status'], name='core_rawrec_tenant__e52435_idx'),
        ),
        migrations.AddIndex(
            model_name='rawrecord',
            index=models.Index(fields=['tenant', 'source_type', 'created_at'], name='core_rawrec_tenant__bc85b4_idx'),
        ),
        migrations.AddIndex(
            model_name='plant',
            index=models.Index(fields=['tenant', 'code'], name='core_plant_tenant__685b09_idx'),
        ),
        migrations.AddConstraint(
            model_name='plant',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uq_plant_tenant_code'),
        ),
        migrations.AddIndex(
            model_name='ingestionjob',
            index=models.Index(fields=['tenant', 'created_at'], name='core_ingest_tenant__35514f_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionjob',
            index=models.Index(fields=['tenant', 'source_type', 'status'], name='core_ingest_tenant__cbfc4e_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionfactor',
            index=models.Index(fields=['tenant', 'category', 'subcategory', 'unit'], name='core_emissi_tenant__7eae36_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionfactor',
            index=models.Index(fields=['is_active', 'valid_from', 'valid_to'], name='core_emissi_is_acti_a101b2_idx'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['tenant', 'review_status', 'created_at'], name='core_activi_tenant__de5291_idx'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['tenant', 'category', 'subcategory'], name='core_activi_tenant__235aa4_idx'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['tenant', 'source_type', 'activity_date'], name='core_activi_tenant__babde8_idx'),
        ),
        migrations.AddIndex(
            model_name='activitychangelog',
            index=models.Index(fields=['tenant', 'activity_record', 'created_at'], name='core_activi_tenant__ee288e_idx'),
        ),
    ]
