# Generated by Django 5.2.14 on 2026-05-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityrecord',
            name='category',
            field=models.CharField(choices=[('fuel_combustion', 'Fuel combustion'), ('purchased_electricity', 'Purchased electricity'), ('business_travel', 'Business travel'), ('procurement', 'Procurement')], max_length=40),
        ),
        migrations.AlterField(
            model_name='emissionfactor',
            name='category',
            field=models.CharField(choices=[('fuel_combustion', 'Fuel combustion'), ('purchased_electricity', 'Purchased electricity'), ('business_travel', 'Business travel'), ('procurement', 'Procurement')], max_length=40),
        ),
    ]
